-- Migracao: Cadastro de Boletos (Financeiro)
-- Planos de boletos (turma ou individual) + boletos emitidos

CREATE TABLE IF NOT EXISTS billet_plans (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  type ENUM('turma','individual') NOT NULL DEFAULT 'individual',
  turma_id INT UNSIGNED DEFAULT NULL,
  course_id INT UNSIGNED DEFAULT NULL,
  user_id INT UNSIGNED DEFAULT NULL COMMENT 'Aluno alvo quando type = individual',
  installments_total INT UNSIGNED NOT NULL DEFAULT 1,
  installment_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  discount_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  first_due_date DATE NOT NULL,
  due_day INT UNSIGNED DEFAULT NULL COMMENT 'Dia fixo de vencimento; NULL = a cada interval_days',
  interval_days INT UNSIGNED NOT NULL DEFAULT 30,
  description VARCHAR(255) DEFAULT NULL,
  status ENUM('active','inactive') NOT NULL DEFAULT 'active',
  created_by INT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_billet_plans_turma (turma_id),
  KEY idx_billet_plans_user (user_id),
  KEY idx_billet_plans_course (course_id),
  KEY idx_billet_plans_type (type),
  CONSTRAINT billet_plans_ibfk_turma FOREIGN KEY (turma_id) REFERENCES turmas(id) ON DELETE CASCADE,
  CONSTRAINT billet_plans_ibfk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT billet_plans_ibfk_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS boletos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  plan_id INT UNSIGNED DEFAULT NULL,
  user_id INT UNSIGNED NOT NULL,
  turma_id INT UNSIGNED DEFAULT NULL,
  course_id INT UNSIGNED DEFAULT NULL,
  installment_number INT UNSIGNED NOT NULL DEFAULT 1,
  installment_total INT UNSIGNED NOT NULL DEFAULT 1,
  description VARCHAR(255) DEFAULT NULL,
  original_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  discount_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  due_date DATE NOT NULL,
  status ENUM('pending','paid','overdue','cancelled','error') NOT NULL DEFAULT 'pending',
  gateway ENUM('efibank','manual') NOT NULL DEFAULT 'efibank',
  charge_id VARCHAR(100) DEFAULT NULL,
  boleto_url VARCHAR(500) DEFAULT NULL,
  barcode VARCHAR(255) DEFAULT NULL,
  gateway_status VARCHAR(50) DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  paid_value DECIMAL(10,2) DEFAULT NULL,
  paid_at DATETIME DEFAULT NULL,
  confirmed_by INT UNSIGNED DEFAULT NULL,
  created_by INT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_boletos_user (user_id),
  KEY idx_boletos_turma (turma_id),
  KEY idx_boletos_plan (plan_id),
  KEY idx_boletos_status (status),
  KEY idx_boletos_due (due_date),
  KEY idx_boletos_charge (charge_id),
  CONSTRAINT boletos_ibfk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT boletos_ibfk_turma FOREIGN KEY (turma_id) REFERENCES turmas(id) ON DELETE CASCADE,
  CONSTRAINT boletos_ibfk_plan FOREIGN KEY (plan_id) REFERENCES billet_plans(id) ON DELETE SET NULL,
  CONSTRAINT boletos_ibfk_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
