-- Amplia a tabela leads para o cadastro completo (import em lote de alunos)
ALTER TABLE leads
  ADD COLUMN source_detail VARCHAR(255) DEFAULT NULL AFTER source,
  ADD COLUMN rg VARCHAR(40) DEFAULT NULL AFTER cpf,
  ADD COLUMN ra VARCHAR(40) DEFAULT NULL AFTER rg,
  ADD COLUMN data_nascimento DATE DEFAULT NULL AFTER ra,
  ADD COLUMN sexo CHAR(1) DEFAULT NULL AFTER data_nascimento,
  ADD COLUMN endereco VARCHAR(255) DEFAULT NULL AFTER sexo,
  ADD COLUMN numero VARCHAR(20) DEFAULT NULL AFTER endereco,
  ADD COLUMN complemento VARCHAR(100) DEFAULT NULL AFTER numero,
  ADD COLUMN bairro VARCHAR(100) DEFAULT NULL AFTER complemento,
  ADD COLUMN cidade VARCHAR(100) DEFAULT NULL AFTER bairro,
  ADD COLUMN estado VARCHAR(2) DEFAULT NULL AFTER cidade,
  ADD COLUMN cep VARCHAR(10) DEFAULT NULL AFTER estado,
  ADD COLUMN naturalidade VARCHAR(100) DEFAULT NULL AFTER cep,
  ADD COLUMN situacao VARCHAR(50) DEFAULT NULL AFTER naturalidade,
  ADD COLUMN data_cadastro DATE DEFAULT NULL AFTER situacao,
  ADD COLUMN responsavel VARCHAR(150) DEFAULT NULL AFTER data_cadastro,
  ADD COLUMN responsavel_whatsapp VARCHAR(20) DEFAULT NULL AFTER responsavel,
  ADD COLUMN responsavel_telefone VARCHAR(20) DEFAULT NULL AFTER responsavel_whatsapp,
  ADD COLUMN escola VARCHAR(200) DEFAULT NULL AFTER responsavel_telefone,
  ADD COLUMN serie_grau VARCHAR(100) DEFAULT NULL AFTER escola,
  ADD COLUMN local_trabalho VARCHAR(150) DEFAULT NULL AFTER serie_grau,
  ADD COLUMN titulo_eleitor VARCHAR(30) DEFAULT NULL AFTER local_trabalho,
  ADD COLUMN observacoes TEXT DEFAULT NULL AFTER titulo_eleitor;
